name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '357.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Build and push Docker images
      run: |
        export IMAGE_NAME = printsome
        docker-compose build
        docker tag ${IMAGE_NAME}_myappprintsome gcr.io/${{ secrets.GCP_PROJECT_ID }}/${IMAGE_NAME}_myappprintsome
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${IMAGE_NAME}_myappprintsome
        
    - name: Deploy to Cloud Run
      run: |
        export IMAGE_NAME=printsome
        gcloud run deploy my-service-printsome --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${IMAGE_NAME}_myappprintsome --platform=managed --region=us-central1 --allow-unauthenticated
