name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure Google Cloud SDK
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Build and push Docker images
    #push to container repo #
      run: |
        export IMAGE_NAME=train-git
        gcloud auth configure-docker
        docker-compose build
        docker tag ${IMAGE_NAME} us-central1-docker.pkg.dev/facebook-scraping-373515/cloud-run-source-deploy/facebook-scraping-373515/${IMAGE_NAME}
        docker push us-central1-docker.pkg.dev/facebook-scraping-373515/cloud-run-source-deploy/facebook-scraping-373515/${IMAGE_NAME}
        
    - name: Deploy to Cloud Run
      run: |
        export IMAGE_NAME=train-git
        gcloud run deploy my-service-printsome --image=us-central1-docker.pkg.dev/facebook-scraping-373515/cloud-run-source-deploy/facebook-scraping-373515/${IMAGE_NAME} --platform=managed --region=us-central1 --allow-unauthenticated
